authors:
  TechxArtisan:
    name: TechxArtisan Studio
    description: Un estudio creativo y comunidad de entusiastas de la tecnología.
    avatar: /images/txa-avatar.jpg

  Openterface:
    name: Openterface
    description: ¡Hola!
    avatar: /images/op-avatar.jpg