flatten_single_child_sections: true
nav:
    - Inicio: index.md
    - Preguntas Frecuentes: faq
    - Producto: product
    - Aplicación: app
    - Casos de Uso: use-cases.md
    - Reseñas: /product/minikvm/reviews/
    - Cumplimiento: compliance.md
    - Tienda: https://shop.techxartisan.com
    - Discord: /discord
    - Blog: blog
    - Acerca de: about.md
